name: Maven Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt' # or 'temurin' or 'zulu' depending on your preference

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Upload JAR
      uses: actions/upload-artifact@v2
      with:
        name: jar
        path: target/*.jar
