name: Maven Build

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the build on
  pull_request:
    branches:
      - main  # Change this to the branch you want to trigger the build on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'  # Change this to your desired Java version

    - name: Build with Maven
      run: mvn -B clean package  # Change this command as per your Maven goals

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: jar
        path: target/*.jar  # Adjust the path to your built artifacts
